

Language = {
    ["pt"] = {
        -- Targets
        openInsuranceMenu = "Abrir Menu do Seguro",
        openHealthInsuranceMenu = "Abrir Menu do Seguro de Saúde",
        openHomeInsuranceMenu = "Abrir Menu do Seguro de Casa",
        
        -- Notificações
        vehicleAlreadyRegisted = "Este veículo já está registado.",
        vehicleRegistedSuccessfully = "Veículo registado com sucesso.",
        vehicleFailedRegisted = "Falha ao registar o veículo.",
        vehicleAlreadyInsured = "Este veículo já está segurado.",
        vehicleInsuredSuccessfully = "Seguro do veículo concluído com sucesso.",
        vehicleFailedInsured = "Falha ao realizar o seguro do veículo.",
        insuranceDocumentsRecover = "Documentação do seguro recuperada com sucesso!",
        vehicleDontHaveInsurance = "Este veículo não possui seguro.",
        registrationDocumentsRecover = "Documentação de registo recuperada com sucesso!",
        vehicleDontHaveRegistration = "Este veículo não possui registo.",
        noMoneyToRecoverDocuments = "Não tens dinheiro suficiente para recuperar os documentos.",
        invalidDocumentType = "Tipo de documento inválido.",
        invalidAccidentData = "Dados do relatório de acidente inválidos recebidos.",
        vehicleHasBeenReportedStolen = "O veículo foi reportado como roubado.",
        vehicleAlreadyReportedStolen = "O veículo já foi reportado como roubado.",
        vehicleRecoveredSuccessfully = "O veículo foi recuperado com sucesso.",
        failedToRecoverVehicle = "Falha ao recuperar o veículo.",
        accidentReportSaved = "Relatório de acidente guardado com sucesso.",
        accidentReportFailed = "Falha ao guardar o relatório de acidente.",
        accidentReportUpdated = "Relatório de acidente atualizado com sucesso.",
        accidentReportUpdateFailed = "Falha ao atualizar o relatório de acidente.",
        accidentReportDeleted = "Relatório de acidente apagado com sucesso.",
        accidentReportDeleteFailed = "Falha ao apagar o relatório de acidente.",
        vehicleDocumentsSuspended = "Os documentos do veículo foram suspensos.",
        vehicleDocumentsAlreadySuspended = "Os documentos do veículo já estão suspensos.",
        vehicleDocumentsRecovered = "Os documentos do veículo foram recuperados.",
        vehicleDocumentsAlreadyRecovered = "Os documentos do veículo já foram recuperados.",
        playerDataNotFound = "Dados do jogador não encontrados.",
        insuranceRemovedSuccessfully = "Seguro removido com sucesso.",
        insuranceFailedRemove = "Falha ao remover o seguro.",
        registrationRemoveSuccessfully = "Registo removido com sucesso.",
        registrationFailedRemove = "Falha ao remover o registo.",
        healthInsuranceAlreadyPurchased = "Já tens seguro de saúde.",
        healthInsurancePurchasedSuccessfully = "Compraste o seguro de saúde com sucesso.",
        healthInsuranceFailedToPurchase = "Ocorreu um erro ao comprar o seguro de saúde.",
        healthInsuranceNotEnoughMoney = "Não tens dinheiro suficiente para comprar o seguro de saúde.",
        healthInsurancePlayerAlreadyHasInsurance = "Esse jogador já tem seguro de saúde.",
        healthInsuranceSuccessfullyPurchasedForPlayer = "Compraste com sucesso o seguro de saúde para %s.",
        healthInsuranceRecoveryFailed = "Falha ao recuperar o seguro de saúde.",
        healthInsuranceRecoverySuccessful = "Recuperaste com sucesso o seguro de saúde para %s.",
        healthInsuranceNotFound = "Esse jogador não tem seguro de saúde.",
        healthInsuranceDocumentationNotEnoughMoney = "Não tens dinheiro suficiente para recuperar a documentação do seguro de saúde.",
        healthInsuranceDocumentationRecoveredSuccessfully = "Recuperaste com sucesso a documentação do seguro de saúde.",
        healthInsuranceDocumentationRecoveryFailed = "Falha ao recuperar a documentação do seguro de saúde.",
        
        homeInsuranceAlreadyPurchased = "Já tens seguro de casas.",
        homeInsurancePurchasedSuccessfully = "Compraste o seguro de casa com sucesso.",
        homeInsuranceFailedToPurchase = "Ocorreu um erro ao comprar o seguro de casa.",
        homeInsuranceNotEnoughMoney = "Não tens dinheiro suficiente para comprar o seguro de casa.",
        homeInsurancePlayerAlreadyHasInsurance = "Esse jogador já tem seguro de casa.",
        homeInsuranceSuccessfullyPurchasedForPlayer = "Compraste com sucesso o seguro de casa para %s.",
        homeInsuranceRecoveryFailed = "Falha ao recuperar o seguro de casa.",
        homeInsuranceRecoverySuccessful = "Recuperaste com sucesso o seguro de casa para %s.",
        homeInsuranceNotFound = "Esse jogador não tem seguro de casa.",
        homeInsuranceDocumentationNotEnoughMoney = "Não tens dinheiro suficiente para recuperar a documentação do seguro de casa.",
        homeInsuranceDocumentationRecoveredSuccessfully = "Recuperaste com sucesso a documentação do seguro de casa.",
        homeInsuranceDocumentationRecoveryFailed = "Falha ao recuperar a documentação do seguro de casa.",
        
        cameraBought = "Compraste uma câmera com sucesso.",
        noMoneyToBuyCamera = "Não tens dinheiro suficiente para comprar uma câmera.",
        noInsuranceToBuyCamera = "Não tens seguro no veículo para comprar uma câmera.",
        noInfoCamera = "This camera is not linked to any vehicle.",
        vehNeedToBeInGarage = "O veículo precisa estar fora da garagem para conseguires usar a câmera.",
        cantActiveCamera = "O veículo precisa de estar estacionado ou parado para conseguires usar a câmera.",
        vehStartMoving = "O veículo começou a mover-se, a câmera foi desativada.",
        vehNotFound = "Veículo não encontrado.",
        
        noMoney = "Não tens dinheiro suficiente.",
    },
    ["en"] = {
        -- Targets
        openInsuranceMenu = "Open Insurance Menu",
        openHealthInsuranceMenu = "Open Health Insurance Menu",
        openHomeInsuranceMenu = "Open Home Insurance Menu",
        
        -- Notifications
        vehicleAlreadyRegisted = "This vehicle is already registered.",
        vehicleRegistedSuccessfully = "Vehicle registered successfully.",
        vehicleFailedRegisted = "Failed to register the vehicle.",
        vehicleAlreadyInsured = "This vehicle is already insured.",
        vehicleInsuredSuccessfully = "Vehicle insurance completed successfully.",
        vehicleFailedInsured = "Failed to insure the vehicle.",
        insuranceDocumentsRecover = "Insurance documents successfully recovered!",
        vehicleDontHaveInsurance = "This vehicle does not have insurance.",
        registrationDocumentsRecover = "Registration documents successfully recovered!",
        vehicleDontHaveRegistration = "This vehicle does not have registration.",
        noMoneyToRecoverDocuments = "You do not have enough money to recover the documents.",
        invalidDocumentType = "Invalid document type.",
        invalidAccidentData = "Invalid accident report data received.",
        vehicleHasBeenReportedStolen = "The vehicle has been reported as stolen.",
        vehicleAlreadyReportedStolen = "The vehicle has already been reported as stolen.",
        vehicleRecoveredSuccessfully = "The vehicle was successfully recovered.",
        failedToRecoverVehicle = "Failed to recover the vehicle.",
        accidentReportSaved = "Accident report saved successfully.",
        accidentReportFailed = "Failed to save the accident report.",
        accidentReportUpdated = "Accident report updated successfully.",
        accidentReportUpdateFailed = "Failed to update the accident report.",
        accidentReportDeleted = "Accident report deleted successfully.",
        accidentReportDeleteFailed = "Failed to delete the accident report.",
        vehicleDocumentsSuspended = "Vehicle documents have been suspended.",
        vehicleDocumentsAlreadySuspended = "Vehicle documents are already suspended.",
        vehicleDocumentsRecovered = "Vehicle documents have been recovered.",
        vehicleDocumentsAlreadyRecovered = "Vehicle documents have already been recovered.",
        playerDataNotFound = "Player data not found.",
        insuranceRemovedSuccessfully = "Insurance removed successfully.",
        insuranceFailedRemove = "Failed to remove the insurance.",
        registrationRemoveSuccessfully = "Registration removed successfully.",
        registrationFailedRemove = "Failed to remove the registration.",
        healthInsuranceAlreadyPurchased = "You already have health insurance.",
        healthInsurancePurchasedSuccessfully = "You successfully purchased health insurance.",
        healthInsuranceFailedToPurchase = "An error occurred while purchasing health insurance.",
        healthInsuranceNotEnoughMoney = "You do not have enough money to purchase health insurance.",
        healthInsurancePlayerAlreadyHasInsurance = "This player already has health insurance.",
        healthInsuranceSuccessfullyPurchasedForPlayer = "You successfully purchased health insurance for %s.",
        healthInsuranceRecoveryFailed = "Failed to recover health insurance.",
        healthInsuranceRecoverySuccessful = "Successfully recovered health insurance for %s.",
        healthInsuranceNotFound = "This player does not have health insurance.",
        healthInsuranceDocumentationNotEnoughMoney = "You do not have enough money to recover health insurance documentation.",
        healthInsuranceDocumentationRecoveredSuccessfully = "Successfully recovered health insurance documentation.",
        healthInsuranceDocumentationRecoveryFailed = "Failed to recover health insurance documentation.",
        
        homeInsuranceAlreadyPurchased = "You already have home insurance.",
        homeInsurancePurchasedSuccessfully = "You successfully purchased home insurance.",
        homeInsuranceFailedToPurchase = "An error occurred while purchasing home insurance.",
        homeInsuranceNotEnoughMoney = "You do not have enough money to purchase home insurance.",
        homeInsurancePlayerAlreadyHasInsurance = "This player already has home insurance.",
        homeInsuranceSuccessfullyPurchasedForPlayer = "You successfully purchased home insurance for %s.",
        homeInsuranceRecoveryFailed = "Failed to recover home insurance.",
        homeInsuranceRecoverySuccessful = "Successfully recovered home insurance for %s.",
        homeInsuranceNotFound = "This player does not have home insurance.",
        homeInsuranceDocumentationNotEnoughMoney = "You do not have enough money to recover home insurance documentation.",
        homeInsuranceDocumentationRecoveredSuccessfully = "Successfully recovered home insurance documentation.",
        homeInsuranceDocumentationRecoveryFailed = "Failed to recover home insurance documentation.",

        cameraBought = "You successfully bought a camera.",
        noMoneyToBuyCamera = "You do not have enough money to buy a camera.",
        noInsuranceToBuyCamera = "You do not have insurance on the vehicle to buy a camera.",
        noInfoCamera = "This camera is not linked to any vehicle.",
        vehNeedToBeInGarage = "The vehicle needs to be out of the garage to be able to use the camera.",
        cantActiveCamera = "The vehicle needs to be parked or stopped to be able to use the camera.",
        vehStartMoving = "The vehicle started moving, the camera was disabled.",
        vehNotFound = "Vehicle not found.",
        
        noMoney = "You do not have enough money.",
    }  
}
